### ISSUE TITLE
delay_us函数问题

### ISSUE THREAD

**Issue by mian2018** [GorgonMeducer/perf_counter#1]
1.延时函数调用了  start_cycle_counter(); 和 stop_cycle_counter()来实现计时功能，因此当在使用start_cycle_counter(); 和 stop_cycle_counter()测量代码运行周期时，代码段中不能使用delay_us() 函数 
2.当延时时间在1-20us时，延时时间不太准

**Comment by GorgonMeducer** [comment]
没错，delay_us() 不能在 start_cycle_counter() 和 stop_cycle_counter() 之间使用，建议用新的 get_system_ticks() 来取代原本的这两个函数。

对于1~20us不准的问题，目前暂无办法，因为有系统性的误差——当系统频率较高时，这一问题会缓解很多。当系统频率较低时，这一问题会比较突出。

**Comment by GorgonMeducer** [comment]
delay_us() 不能跟 start_cycle_counter() 和 stop_cycle_counter() 一起使用的问题解决了。

**Comment by LusterWong** [comment]
> 没错，delay_us() 不能在 start_cycle_counter() 和 stop_cycle_counter() 之间使用，建议用新的 get_system_ticks() 来取代原本的这两个函数。如果可能，用 **cycleof**() 来测量周期数。
> 
> 对于1~20us不准的问题，目前暂无办法，因为有系统性的误差——当系统频率较高时，这一问题会缓解很多。当系统频率较低时，这一问题会比较突出。但理论上，这一误差也就是在 +/- 25个cycle左右……

系统性误差是指什么东西？流水线还是什么MCU缓存吗？还是中断原因？
如果是中断原因如果调用时没中断插手应该不存在这个问题吧。

**Comment by GorgonMeducer** [comment]
> > 没错，delay_us() 不能在 start_cycle_counter() 和 stop_cycle_counter() 之间使用，建议用新的 get_system_ticks() 来取代原本的这两个函数。如果可能，用 **cycleof**() 来测量周期数。
> > 对于1~20us不准的问题，目前暂无办法，因为有系统性的误差——当系统频率较高时，这一问题会缓解很多。当系统频率较低时，这一问题会比较突出。但理论上，这一误差也就是在 +/- 25个cycle左右……
> 
> 系统性误差是指什么东西？流水线还是什么MCU缓存吗？还是中断原因？
> 如果是中断原因如果调用时没中断插手应该不存在这个问题吧。

系统性误差很好理解：
比如你要延时 n 个cycle（从us换算来的），在某次检查时，函数发现现在是 n-1，显然没到时间，然后就退出去了，下次进来检查，因为函数本身有开销，所以可能实际返回的时候已经是 n+25了……这就是消除不掉的系统性误差，而且是摆动的。
