### ISSUE TITLE
deal with timestamp rollover

### ISSUE THREAD

**Issue by marshfolx** [GorgonMeducer/perf_counter#26]
Base on practices from arduino community, a delay function should not compare timestamps. The preferred manner is to calculate time duration. So I think `delay_ms` and `delay_us` should be modified a bit. 

The original code is:

```c
void delay_us(int32_t nUs)
{
    int64_t lUs = (int64_t)nUs * (int64_t)s_nUSUnit;
    int32_t iCompensate = g_nOffset > PERF_CNT_DELAY_US_COMPENSATION
                        ? g_nOffset 
                        : PERF_CNT_DELAY_US_COMPENSATION;

    if (lUs <= iCompensate) {
        return ;
    }

    lUs -= iCompensate;

    lUs += get_system_ticks();
    while(get_system_ticks() < lUs);
}


void delay_ms(int32_t nMs)
{
    int64_t lUs = (int64_t)nMs * (int64_t)s_nMSUnit;
    int32_t iCompensate = g_nOffset > PERF_CNT_DELAY_US_COMPENSATION
                        ? g_nOffset 
                        : PERF_CNT_DELAY_US_COMPENSATION;

    if (lUs <= iCompensate) {
        return ;
    }

    lUs -= iCompensate;

    lUs += get_system_ticks();
    while(get_system_ticks() < lUs);
}
```

Below the modification may be fine:

```c
void delay_tick(uint64_t tick) {
    int32_t iCompensate = g_nOffset > PERF_CNT_DELAY_US_COMPENSATION
                        ? g_nOffset 
                        : PERF_CNT_DELAY_US_COMPENSATION;

    if (tick <= iCompensate) {
        return ;
    }
    
    tick -= iCompensate;

    int64_t t = get_system_ticks();
    while((get_system_ticks() - t) < tick);
}


__always_inline void delay_us(int32_t nUs)
{
    delay_tick((int64_t)nUs * (int64_t)s_nUSUnit);
}


__always_inline void delay_ms(int32_t nMs)
{
    delay_tick((int64_t)nMs * (int64_t)s_nMSUnit);
}
```

**Comment by GorgonMeducer** [comment]
> Base on practices from arduino community, a delay function should not compare timestamps.

Can I know why? I didn't know the history or the background. Sorry, I cannot accept any rule that I don't fully understand. 
So what's the drawback?

@marshfolx  Thank you in advance.

**Comment by marshfolx** [comment]
> > Base on practices from arduino community, a delay function should not compare timestamps.
> 
> Can I know why? I didn't know the history or the background. Sorry, I cannot accept any rule that I don't fully understand. So what's the drawback?
> 
> @marshfolx Thank you in advance.

~~Because by `lUs += get_system_ticks()`, as `lUS` is unsigned integer, there are chances that `lUs` is less than get_system_ticks() if my understanding about your code is correct. Someone have made some excellent explanations about this: https://arduino.stackexchange.com/questions/12587/how-can-i-handle-the-millis-rollover~~

OK, my fault, `lUs` is signed. I think it's not common to use signed int64 to store timestamp. Can you explain a bit?

**Comment by GorgonMeducer** [comment]
> I think it's not common to use signed int64 to store timestamp.

Please allow me to have a different understanding of the "common". 

perf_counter is designed for Cortex-M processors which are 32bit.
The 32-bit timestamp will face the overflow issue as some devices have over 1GHz frequency. To avoid overflow, choosing 64bit is an ideal solution and the calculation cost isn't big in a 32bit system.

**Comment by marshfolx** [comment]
> To avoid overflow, choosing 64bit is an ideal solution and the calculation cost isn't big in a 32bit system.

Yes 64bit can last very very long time than 32bit even longer than human lifetime. But, as many other applications do, usually the unsigned integer is prefered, either uint32_t or uint64_t, to represent time. Because for a "common" application, time always grow from 0 and the negative value of time is meaningless. But there may be some benefits where my qustion actually focuses.

**Comment by GorgonMeducer** [comment]
> But there may be some benefits where my qustion actually focuses.

Yes, using signed 64bit makes the equation simple:

https://github.com/GorgonMeducer/perf_counter/blob/d4855492b1e933fd28a87afcac031e0b16cc46b1/perf_counter.c#L270-L301

Sorry, my fault, here is some history, we should check the earlier version:

https://github.com/GorgonMeducer/perf_counter/blob/097f387bf993ff726ad1d2ed3a31aeee73902d43/perf_counter.c#L224-L288

As you can see, inside the `start_cycle_counter()` the `s_nCycleCounts` is negative. In the later version, although we changed the implementation of `start_cycle_counter()`, the prototype is fixed plus we found another reason to use a signed integer.

**Comment by GorgonMeducer** [comment]
Another obvious reason is, perf_counter offers calibration:

https://github.com/GorgonMeducer/perf_counter/blob/d4855492b1e933fd28a87afcac031e0b16cc46b1/perf_counter.c#L237-L246

Here `g_nOffset` is used to remove the overhead of calling those functions. 
But due to compiler optimization, i.e. `-Ofast + LTO`, `-Omax`, etc, the measured result (using `__cycleof__()`) might actually be smaller than `g_nOffset`. For this case, if we use `uint64_t`, the calibrated result will be very big, i.e. `0xFFFF...` but if we use a signed integer, the calibrated result will be a small negative value that can be filtered or explained in the performance analysis. 

I hope this helps.

**Comment by marshfolx** [comment]
@GorgonMeducer OK, sign is fine. This issue can be closed.
