### ISSUE TITLE
support for ThreadX RTOS

### ISSUE THREAD

**Issue by Linjieqiang** [GorgonMeducer/perf_counter#3]

**Comment by GorgonMeducer** [comment]
好的，安排上。关键是我要先搞定ThreadX的测试环境。

**Comment by GorgonMeducer** [comment]
我看了下， ThreadX自带了统计功能……真的需要perf_counter么？

**Comment by GorgonMeducer** [comment]
大约知道怎么搞了。就是定义宏 TX_ENABLE_EXECUTION_CHANGE_NOTIFY，然后去 劫持 
_tx_execution_thread_enter() 和 
_tx_execution_thread_exit()

**Comment by GorgonMeducer** [comment]
ThreadX 支持已经添加。

**Comment by GorgonMeducer** [comment]
由于cmsis-pack目前MDK支持上的限制，在使用 ThreadX 的patch时，需要用户收工在 Asm 的配置里加入 -include "Pre_Include_Global.h"

![image](https://user-images.githubusercontent.com/13148491/147741999-80d4fe23-c32a-4ba5-b242-016b72ca220e.png)

**Comment by GorgonMeducer** [comment]
尽可能避免用 port下 ac5 的汇编，因为目前 MDK 没有很好的方法来支持 ac5汇编中的 C语言预处理。

**Comment by GorgonMeducer** [comment]
请使用 1.7.5 这个版本

https://github.com/GorgonMeducer/perf_counter/releases/tag/v1.7.5

**Comment by Linjieqiang** [comment]
太棒了 感谢
