### ISSUE TITLE
__cycleof__宏 测量出来的结果为负数

### ISSUE THREAD

**Issue by CofeCofe** [GorgonMeducer/perf_counter#33]
在main函数的死循环中 反复 使用 __cycleof__对函数运行时间进行测量，发现偶尔会出现测量结果为 **负数** 的情况。get_system_ticks()函数中有提及在更高优先级的异常处理函数中使用的问题，和我这里场景不大相同。

**Comment by GorgonMeducer** [comment]
负数的数值大么？可以提供一个测量结果的截图看看？
如果负数值很小，则可以忽略。

**Comment by CofeCofe** [comment]
> 负数的数值大么？可以提供一个测量结果的截图看看？ 如果负数值很小，则可以忽略。

![屏幕截图 2024-07-03 224613](https://github.com/GorgonMeducer/perf_counter/assets/173254032/41b746c8-8e88-4df0-81f2-91e5cde26f5f)

**Comment by CofeCofe** [comment]
> 负数的数值大么？可以提供一个测量结果的截图看看？ 如果负数值很小，则可以忽略。

这个是调用的代码
```c
for (;;) {

        __cycleof__("led_yellow") {
            led_yellow();
        }
        __cycleof__("print_yellow") {
            printf("yellow\n");
        }
        delay_ms(500);
        led_black();
//        printf("black\n");
        delay_ms(500);
    }
```

**Comment by CofeCofe** [comment]
> > 负数的数值大么？可以提供一个测量结果的截图看看？ 如果负数值很小，则可以忽略。
> 
> 这个是调用的代码
> 
> ```c
> for (;;) {
> 
>         __cycleof__("led_yellow") {
>             led_yellow();
>         }
>         __cycleof__("print_yellow") {
>             printf("yellow\n");
>         }
>         delay_ms(500);
>         led_black();
> //        printf("black\n");
>         delay_ms(500);
>     }
> ```

printf就普通的重定向，用的串口阻塞输出，led操作就是普通GPIO高低电平的变化

**Comment by GorgonMeducer** [comment]
优化等级多少？这里 `led_yellow()` 大概率是被编译器 inline 掉了。
你可以尝试给 led_yellow() 加入 `__attribute__((noinline))`

可以试试【只】把这段测试代码（【而不是】要测试的目标函数）的优化等级设置为 -O0。
也就是这段代码所在函数：
```c
for (;;) {

        __cycleof__("led_yellow") {
            led_yellow();
        }
        __cycleof__("print_yellow") {
            printf("yellow\n");
        }
        delay_ms(500);
        led_black();
//        printf("black\n");
        delay_ms(500);
    }
```

也可以试试在测试前把校准变量 `g_nOffset` 设置为`0`. 一般优化等级比较高的时候，推荐把 `g_nOffset` 设置为0来避免出现负数的情况。

**Comment by CofeCofe** [comment]
> 优化等级多少？这里 `led_yellow()` 大概率是被编译器 inline 掉了。 你可以尝试给 led_yellow() 加入 `__attribute__((noinline))`
> 
> 可以试试【只】把这段测试代码（【而不是】要测试的目标函数）的优化等级设置为 -O0。 也就是这段代码所在函数：
> 
> ```c
> for (;;) {
> 
>         __cycleof__("led_yellow") {
>             led_yellow();
>         }
>         __cycleof__("print_yellow") {
>             printf("yellow\n");
>         }
>         delay_ms(500);
>         led_black();
> //        printf("black\n");
>         delay_ms(500);
>     }
> ```
> 
> 也可以试试在测试前把校准变量 `g_nOffset` 设置为`0`. 一般优化等级比较高的时候，推荐把 `g_nOffset` 设置为0来避免出现负数的情况。

AC6开的Oz，目前测试了下
1. 单独给led_yellow加入__attribute__((noinline))，仍然会出现上述情况
2. 把所有代码编译优化等级改为O0，测试了半小时没出现负数
3. led_yellow 设置noinline，for所在的函数设置优化等级为O0，仍然会出现负数。
我怀疑是不是单独设置O0等级的优化没有生效？
```c
__NO_RETURN
static void test(void) __attribute__((optnone)){
    for(;;){
        ...
    }
}
```

**Comment by CofeCofe** [comment]
> > 优化等级多少？这里 `led_yellow()` 大概率是被编译器 inline 掉了。 你可以尝试给 led_yellow() 加入 `__attribute__((noinline))`
> > 可以试试【只】把这段测试代码（【而不是】要测试的目标函数）的优化等级设置为 -O0。 也就是这段代码所在函数：
> > ```c
> > for (;;) {
> > 
> >         __cycleof__("led_yellow") {
> >             led_yellow();
> >         }
> >         __cycleof__("print_yellow") {
> >             printf("yellow\n");
> >         }
> >         delay_ms(500);
> >         led_black();
> > //        printf("black\n");
> >         delay_ms(500);
> >     }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 也可以试试在测试前把校准变量 `g_nOffset` 设置为`0`. 一般优化等级比较高的时候，推荐把 `g_nOffset` 设置为0来避免出现负数的情况。
> 
> AC6开的Oz，目前测试了下
> 
> 1. 单独给led_yellow加入__attribute__((noinline))，仍然会出现上述情况
> 2. 把所有代码编译优化等级改为O0，测试了半小时没出现负数
> 3. led_yellow 设置noinline，for所在的函数设置优化等级为O0，仍然会出现负数。
>    我怀疑是不是单独设置O0等级的优化没有生效？
> 
> ```c
> __NO_RETURN
> static void test(void) __attribute__((optnone)){
>     for(;;){
>         ...
>     }
> }
> ```

我搜到了这个 https://developer.arm.com/documentation/ka002242/latest/

Unfortunately, there is no other way. The Arm compiler 6.x does not support changing optimization options within a C-source file. Instead these must be set on a per-file basis using command-line options. If you have functions that absolutely need different optimization levels, you need to put them into different C-source files.

== 好像不支持这个attribute

**Comment by CofeCofe** [comment]
> 优化等级多少？这里 `led_yellow()` 大概率是被编译器 inline 掉了。 你可以尝试给 led_yellow() 加入 `__attribute__((noinline))`
> 
> 可以试试【只】把这段测试代码（【而不是】要测试的目标函数）的优化等级设置为 -O0。 也就是这段代码所在函数：
> 
> ```c
> for (;;) {
> 
>         __cycleof__("led_yellow") {
>             led_yellow();
>         }
>         __cycleof__("print_yellow") {
>             printf("yellow\n");
>         }
>         delay_ms(500);
>         led_black();
> //        printf("black\n");
>         delay_ms(500);
>     }
> ```
> 
> 也可以试试在测试前把校准变量 `g_nOffset` 设置为`0`. 一般优化等级比较高的时候，推荐把 `g_nOffset` 设置为0来避免出现负数的情况。

又测试了两种情况
1. 单独设置for所在的.c的优化等级为-O0，仍有负数
2. 将for代码所在的xx.c文件和【perf_counter.c】的优化等级也设置为-O0，没有出现负数了

**Comment by GorgonMeducer** [comment]
> 好像不支持这个attribute

支持的。这是[LLVM带的](https://clang.llvm.org/docs/AttributeReference.html#optnone)。

另外把 g_nOffset设置为0 的方法你好像没测试？

> 将for代码所在的xx.c文件和【perf_counter.c】的优化等级也设置为-O0，没有出现负数了

你可以试试只把 perf_counter.c 设置为 -O0 看看。

**Comment by CofeCofe** [comment]
> > 好像不支持这个attribute
> 
> 支持的。这是[LLVM带的](https://clang.llvm.org/docs/AttributeReference.html#optnone)。
> 
> 另外把 g_nOffset设置为0 的方法你好像没测试？
> 
> > 将for代码所在的xx.c文件和【perf_counter.c】的优化等级也设置为-O0，没有出现负数了
> 
> 你可以试试只把 perf_counter.c 设置为 -O0 看看。

1. g_nOffset设置为0后，虽然不会出现负数，但是会出现【0】
2. 【只】把perf_counter.c设置为O0仍然会出现负数
3. for所在xx.c设置为Oz，但是for所在函数(main函数)设置为optnone，perf_counter优化等级设置为O0，也会出现负数
4. for所在xx.c设置为Oz，但是for所在函数(test函数)设置为optnone，perf_counter优化等级设置为O0 会出现负数

![image](https://github.com/GorgonMeducer/perf_counter/assets/173254032/49831b41-9d5a-4feb-a2d4-5db1c895742f)

**Comment by GorgonMeducer** [comment]
> g_nOffset设置为0后，虽然不会出现负数，但是会出现【0】

这就是出现负数的原因。

之所以会出现负数，是编译器激进优化导致的结果。这不是库的bug，也不是库的feature。
知道原理以后，你只能自己想办法了。毕竟 `__cycleof__` 只是我们软件开发过程中的一个辅助测量方法，是帮你进行性能分析的。偶尔出现负数，对性能分析并不存在影响——因为作为人类，我们自己可以判断一个数据是否有效——或者说是否需要保留。

你的看法呢？或者说，你希望我做什么呢？

我能想到的一个可能的解决方案是在被测代码的前后都加一个__NOP()来阻断编译器的激进优化，比如：

```c
for (;;) {

        __cycleof__("led_yellow") {
            __NOP();
            led_yellow();
            __NOP();
        }
        __cycleof__("print_yellow") {
            __NOP();
            printf("yellow\n");
            __NOP();
        }
        delay_ms(500);
        led_black();
//        printf("black\n");
        delay_ms(500);
    }
```

你可以试试这个方法是否有效。

另外一个值得尝试的方法是初始化perf_counter的时候使用：
```c
init_cycle_counter(false);
```

**Comment by CofeCofe** [comment]
> > g_nOffset设置为0后，虽然不会出现负数，但是会出现【0】
> 
> 这就是出现负数的原因。
> 
> 之所以会出现负数，是编译器激进优化导致的结果。这不是库的bug，也不是库的feature。 知道原理以后，你只能自己想办法了。毕竟 `__cycleof__` 只是我们软件开发过程中的一个辅助测量方法，是帮你进行性能分析的。偶尔出现负数，对性能分析并不存在影响——因为作为人类，我们自己可以判断一个数据是否有效——或者说是否需要保留。
> 
> 你的看法呢？或者说，你希望我做什么呢？
> 
> 我能想到的一个可能的解决方案是在被测代码的前后都加一个__NOP()来阻断编译器的激进优化，比如：
> 
> ```c
> for (;;) {
> 
>         __cycleof__("led_yellow") {
>             __NOP();
>             led_yellow();
>             __NOP();
>         }
>         __cycleof__("print_yellow") {
>             __NOP();
>             printf("yellow\n");
>             __NOP();
>         }
>         delay_ms(500);
>         led_black();
> //        printf("black\n");
>         delay_ms(500);
>     }
> ```
> 
> 你可以试试这个方法是否有效。
> 
> 另外一个值得尝试的方法是初始化perf_counter的时候使用：
> 
> ```c
> init_cycle_counter(false);
> ```
感谢大佬解惑，您说的确实没错，在性能分析上出现负数并不影响，其实我这边确实有点钻牛角尖了，哈哈。
不过当初最让我感到诧异编译器执行优化后的效果，【看上去】像是导致执行顺序发生了变化。
我这边有点好奇 在这段代码中 编译器优化的具体行为是什么？或者说是什么样结构的代码造成了编译器如此激进的优化？是嵌套循环？是内联优化？
还有一个问题就是LLVM的__attribute__是不是在AC6中【都】是通用的呢？

**Comment by GorgonMeducer** [comment]
> 还有一个问题就是LLVM的__attribute__是不是在AC6中【都】是通用的呢？

是的。虽然有一些例外，但大部分都适用。

> 我这边有点好奇 在这段代码中 编译器优化的具体行为是什么？或者说是什么样结构的代码造成了编译器如此激进的优化？

你用的是 -Oz，它是AC6提供的最高尺寸优化，编译器会在确保逻辑等效（而不是执行顺序）的前提下调整代码的顺序。具体是怎样的代码结构，这就无法得知了（即便你看了编译原理，这也是不一定的，因为不同版本、不同优化等级、不同idiom组合导致的结果都不是确定的）。

你测试过加 __NOP() 的方法了么？__NOP() 实际上是一个在线汇编，编译器遇到在线汇编的时候，有大概率将其看做某种确保代码执行顺序的 barrier 。所以值得尝试下。

你可以把 g_nOffset设置为0以后，再用加 __NOP() 的方法测试下。看看还会不会出现测量结果为0的情况。
——如果实测有效，我就可以更新库，在 __cycleof__ 里藏下 __NOP() 来确保代码执行顺序。

**Comment by GorgonMeducer** [comment]
另外，你也可以试试用 `__sync_synchronize()` 来阻断编译器更改代码的顺序。比如：
```c
for (;;) {

        __cycleof__("led_yellow") {
            __sync_synchronize();
            led_yellow();
            __sync_synchronize();
        }
        __cycleof__("print_yellow") {
            __sync_synchronize();
            printf("yellow\n");
            __sync_synchronize();
        }
        delay_ms(500);
        led_black();
//        printf("black\n");
        delay_ms(500);
    }
```

**Comment by GorgonMeducer** [comment]
我根据你的情况，加入了宏 `__perfc_sync_barrier__()`，并将其集成到了 `__cycleof__()` 中。
我发布了新版本 [v2.3.2](https://github.com/GorgonMeducer/perf_counter/releases/download/v2.3.2/GorgonMeducer.perf_counter.2.3.2.pack)。你可以测试下。

**Comment by CofeCofe** [comment]
> > 还有一个问题就是LLVM的__attribute__是不是在AC6中【都】是通用的呢？
> 
> 是的。虽然有一些例外，但大部分都适用。
> 
> > 我这边有点好奇 在这段代码中 编译器优化的具体行为是什么？或者说是什么样结构的代码造成了编译器如此激进的优化？
> 
> 你用的是 -Oz，它是AC6提供的最高尺寸优化，编译器会在确保逻辑等效（而不是执行顺序）的前提下调整代码的顺序。具体是怎样的代码结构，这就无法得知了（即便你看了编译原理，这也是不一定的，因为不同版本、不同优化等级、不同idiom组合导致的结果都不是确定的）。
> 
> 你测试过加 __NOP() 的方法了么？__NOP() 实际上是一个在线汇编，编译器遇到在线汇编的时候，有大概率将其看做某种确保代码执行顺序的 barrier 。所以值得尝试下。
> 
> 你可以把 g_nOffset设置为0以后，再用加 __NOP() 的方法测试下。看看还会不会出现测量结果为0的情况。 ——如果实测有效，我就可以更新库，在 **cycleof** 里藏下 __NOP() 来确保代码执行顺序。

抱歉这么久才回复，之前是有测试过添加_NOP()的，但是仍会出现测量结果为0的现象

**Comment by GorgonMeducer** [comment]
我在新版本加了barrier，你测试结果如何？
